## EFFICIENTLY CALCULATING THE INVERSE OF A MATRIX
## Uses caching method to avoid recalculating a previously calculated inverse.
## Program assumes the input matrix is invertable.


## Caches the matrix being used.
## Provides the means to record and recall the matrix and its inverse.
## Input: a square matrix

makeCacheMatrix <- function(x = matrix()) {

            m <- NULL
            set <- function(y) {
                    x <<- y
                    m <<- NULL
            }
            get <- function() x
            setInverse <- function(solve) m <<- solve
            getInverse <- function() m
            list(set = set, get = get,
                 setInverse = setInverse,
                 getInverse = getInverse)
    }



## Checks for previously calculated inverse and recalls it if present.
## Otherwise caches the newly submitted matrix.
## Input: List generated by the makeCacheMatrix function.

cacheSolve <- function(x, ...) {
        ## Return a matrix that is the inverse of 'x'

             m <- x$getInverse()
            if(!is.null(m)) {
                    message("getting cached data")
                    return(m)
            }
            data <- x$get()
            m <- solve(data, ...)
            x$setInverse(m)
            m
    }
